//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMIGOS
    {
        public AMIGOS()
        {
            this.ARRIENDOS_AMIGOS = new HashSet<ARRIENDOS_AMIGOS>();
        }
    
        public decimal ID_AMIGO { get; set; }
        public int RUT { get; set; }
        public string DV { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public System.DateTime FEC_NAC { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<ARRIENDOS_AMIGOS> ARRIENDOS_AMIGOS { get; set; }
    }
}
