//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARRIENDOS
    {
        public ARRIENDOS()
        {
            this.ARRIENDOS_AMIGOS = new HashSet<ARRIENDOS_AMIGOS>();
            this.MULTAS = new HashSet<MULTAS>();
            this.SERVICIOS_CONTRATADOS = new HashSet<SERVICIOS_CONTRATADOS>();
            this.TRANSPORTES_REALIZADOS = new HashSet<TRANSPORTES_REALIZADOS>();
        }
    
        public decimal ID_ARRIENDO { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public decimal ID_DPTO { get; set; }
        public System.DateTime FECHA_RESERVA { get; set; }
        public decimal VALOR_RESERVA { get; set; }
        public string RESERVA_PAGADA { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public string CHECK_IN { get; set; }
        public string CHECK_OUT { get; set; }
        public decimal TOTAL_ARRIENDO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual ICollection<ARRIENDOS_AMIGOS> ARRIENDOS_AMIGOS { get; set; }
        public virtual ICollection<MULTAS> MULTAS { get; set; }
        public virtual ICollection<SERVICIOS_CONTRATADOS> SERVICIOS_CONTRATADOS { get; set; }
        public virtual ICollection<TRANSPORTES_REALIZADOS> TRANSPORTES_REALIZADOS { get; set; }
    }
}
