//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDUCTORES
    {
        public CONDUCTORES()
        {
            this.TRANSPORTES_REALIZADOS = new HashSet<TRANSPORTES_REALIZADOS>();
        }
    
        public int ID_CONDUCTOR { get; set; }
        public string NOMBRE { get; set; }
        public string APE_PAT { get; set; }
        public string APE_MAT { get; set; }
        public string TIPO_LICENCIA { get; set; }
        public System.DateTime FEC_NAC { get; set; }
    
        public virtual ICollection<TRANSPORTES_REALIZADOS> TRANSPORTES_REALIZADOS { get; set; }
    }
}
