//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS_EXTRA
    {
        public SERVICIOS_EXTRA()
        {
            this.DISPONIBILIDAD_SERVICIOS = new HashSet<DISPONIBILIDAD_SERVICIOS>();
            this.SERVICIOS_CONTRATADOS = new HashSet<SERVICIOS_CONTRATADOS>();
        }
    
        public decimal ID_SERVICIO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal COSTO_ACTUAL { get; set; }
    
        public virtual ICollection<DISPONIBILIDAD_SERVICIOS> DISPONIBILIDAD_SERVICIOS { get; set; }
        public virtual ICollection<SERVICIOS_CONTRATADOS> SERVICIOS_CONTRATADOS { get; set; }
    }
}
