//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_USUARIO
    {
        public TIPO_USUARIO()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public short ID_TIPOUSUARIO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
